_this removeItem 'i6AA_CONSUMABLES2';
for "_i" from 1 to 3 do {_this addItemToBackpack "i6AA_Transfusion"};
for "_i" from 1 to 4 do {_this addItemToBackpack "kat_larynx"};
for "_i" from 1 to 4 do {_this addItemToBackpack "ACE_splint"};
for "_i" from 1 to 4 do {_this addItemToBackpack "kat_chestSeal"};
for "_i" from 1 to 2 do {_this addItemToBackpack "kat_ncdKit"};
for "_i" from 1 to 2 do {_this addItemToBackpack "kat_aatKit"};
for "_i" from 1 to 2 do {_this addItemToBackpack "kat_IV_16"};
for "_i" from 1 to 2 do {_this addItemToBackpack "kat_IO_FAST"};
for "_i" from 1 to 2 do {_this addItemToBackpack "KAT_Empty_bloodIV_500"};
for "_i" from 1 to 20 do {_this addItemToBackpack "ace_suture"};