_this removeItem 'i6AA_DRUGS2';
for "_i" from 1 to 5 do {_this addItemToBackpack 'kat_TXA'};
for "_i" from 1 to 5 do {_this addItemToBackpack 'ACE_morphine'};
for "_i" from 1 to 5 do {_this addItemToBackpack 'ACE_epinephrine'};
for "_i" from 1 to 3 do {_this addItemToBackpack 'kat_naloxone'};
for "_i" from 1 to 5 do {_this addItemToBackpack 'kat_EACA'};
for "_i" from 1 to 5 do {_this addItemToBackpack 'kat_phenylephrine'};
for "_i" from 1 to 5 do {_this addItemToBackpack 'kat_lidocaine'};
for "_i" from 1 to 3 do {_this addItemToBackpack 'ACE_adenosine'};
for "_i" from 1 to 5 do {_this addItemToBackpack 'kat_amiodarone'};
_this addItemToBackpack 'kat_Carbonate';
_this addItemToBackpack 'kat_Penthrox';
_this addItemToBackpack 'kat_Painkiller';
