_this removeItem 'i6AA_CONSUMABLES';
for "_i" from 1 to 2 do {_this addItemToBackpack "kat_guedel"};
for "_i" from 1 to 2 do {_this addItemToBackpack "kat_chestSeal"};
for "_i" from 1 to 2 do {_this addItemToBackpack "kat_ncdKit"};
for "_i" from 1 to 2 do {_this addItemToBackpack "ACE_splint"};
for "_i" from 1 to 5 do {_this addItemToBackpack "ACE_EarPlugs"};
for "_i" from 1 to 2 do {_this addItemToBackpack "kat_IV_16"};
for "_i" from 1 to 2 do {_this addItemToBackpack "kat_IO_FAST"};
_this addItemToBackpack "KAT_Empty_bloodIV_250";
_this addItemToBackpack "i6AA_Transfusion";
